# Generated by Django 4.2.3 on 2023-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scname', models.CharField(max_length=100)),
                ('Scloc', models.CharField(max_length=100)),
            ],
        ),
    ]
